import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Helper function to create slug from name
const createSlug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export async function seedProperties(propOwnerId: string) {
  console.log("🏨 Creating properties with room types...");

  // Delete existing properties and room types
  await prisma.roomType.deleteMany();
  await prisma.property.deleteMany();

  const properties = [
    {
      name: "Al Noor Starlet Hotel",
      description: "Luxurious hotel in the heart of Skardu with stunning mountain views. Features modern amenities, comfortable rooms, and exceptional service.",
      type: "HOTEL" as const,
      address: "Main Bazaar Road",
      city: "Skardu",
      country: "Pakistan",
      state: "GB",
      postalCode: "16300",
      maxGuests: 4,
      bedrooms: 2,
      bathrooms: 2,
      beds: 2,
      basePrice: 12000,
      currency: "PKR",
      cleaningFee: 500,
      serviceFee: 300,
      taxRate: 5,
      images: ["/alnoor.png"],
      mainImage: "/alnoor.png",
      amenities: ["WiFi", "Parking", "Restaurant", "AC", "Room Service"],
      propertyFacilities: ["Restaurant", "Gym", "Spa", "Business Center", "Concierge"],
      safetyFeatures: ["24/7 Security", "CCTV", "Fire Safety", "First Aid"],
      accessibility: ["Wheelchair Access", "Elevator", "Accessible Rooms"],
      houseRules: ["No Smoking", "No Pets", "Check-in: 15:00", "Check-out: 11:00"],
      ownerId: propOwnerId,
      approvalStatus: "APPROVED" as const,
      available: true,
      isFeatured: true,
      isVerified: true,
      starRating: 4,
      totalRooms: 25,
      rating: 4.8,
      reviewCount: 50,
      slug: "al-noor-starlet-hotel",
      checkInTime: "15:00",
      checkOutTime: "11:00",
      cancellationPolicy: "Flexible",
      // Room types for this hotel
      roomTypes: [
        {
          name: "Standard Twin Room",
          description: "Comfortable twin room with mountain views, perfect for couples or friends.",
          maxOccupancy: 2,
          adults: 2,
          children: 0,
          bedType: "Twin",
          numberOfBeds: 2,
          bedConfiguration: "2 Twin Beds",
          roomSize: 25,
          roomSizeUnit: "sqm",
          floor: "2nd-4th Floor",
          view: "Mountain View",
          images: ["/alnoor.png"],
          mainImage: "/alnoor.png",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer"],
          basePrice: 8000,
          currency: "PKR",
          weekendPrice: 10000,
          totalUnits: 10,
          available: true,
        },
        {
          name: "Deluxe King Room",
          description: "Spacious room with king bed and panoramic mountain views.",
          maxOccupancy: 2,
          adults: 2,
          children: 0,
          bedType: "King",
          numberOfBeds: 1,
          bedConfiguration: "1 King Bed",
          roomSize: 35,
          roomSizeUnit: "sqm",
          floor: "5th-7th Floor",
          view: "Panoramic Mountain View",
          images: ["/alnoor.png"],
          mainImage: "/alnoor.png",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar", "Balcony"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer", "Sitting Area"],
          basePrice: 12000,
          currency: "PKR",
          weekendPrice: 15000,
          totalUnits: 8,
          available: true,
        },
        {
          name: "Executive Suite",
          description: "Luxurious suite with separate living area and premium amenities.",
          maxOccupancy: 4,
          adults: 2,
          children: 2,
          bedType: "King",
          numberOfBeds: 1,
          bedConfiguration: "1 King Bed + Sofa Bed",
          roomSize: 55,
          roomSizeUnit: "sqm",
          floor: "8th-10th Floor",
          view: "Panoramic Mountain View",
          images: ["/alnoor.png"],
          mainImage: "/alnoor.png",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar", "Balcony", "Separate Living Area"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer", "Sitting Area", "Dining Table"],
          basePrice: 18000,
          currency: "PKR",
          weekendPrice: 22000,
          totalUnits: 5,
          available: true,
        },
      ]
    },
    {
      name: "Legend Hotel",
      description: "Modern hotel with panoramic views of Skardu Valley.",
      type: "HOTEL" as const,
      address: "Airport Road",
      city: "Skardu",
      country: "Pakistan",
      state: "GB",
      postalCode: "16300",
      maxGuests: 3,
      bedrooms: 2,
      bathrooms: 1,
      beds: 2,
      basePrice: 10000,
      currency: "PKR",
      cleaningFee: 400,
      serviceFee: 250,
      taxRate: 5,
      images: ["/legend.jpg"],
      mainImage: "/legend.jpg",
      amenities: ["WiFi", "Restaurant", "AC"],
      propertyFacilities: ["Restaurant", "Parking", "24/7 Front Desk"],
      safetyFeatures: ["24/7 Security", "CCTV", "Fire Safety"],
      accessibility: ["Wheelchair Access", "Elevator"],
      houseRules: ["No Smoking", "Check-in: 14:00", "Check-out: 12:00"],
      ownerId: propOwnerId,
      approvalStatus: "APPROVED" as const,
      available: true,
      isFeatured: false,
      isVerified: true,
      starRating: 3,
      totalRooms: 15,
      rating: 4.6,
      reviewCount: 42,
      slug: "legend-hotel",
      checkInTime: "14:00",
      checkOutTime: "12:00",
      cancellationPolicy: "Moderate",
      roomTypes: [
        {
          name: "Standard Single Room",
          description: "Cozy single room perfect for solo travelers.",
          maxOccupancy: 1,
          adults: 1,
          children: 0,
          bedType: "Single",
          numberOfBeds: 1,
          bedConfiguration: "1 Single Bed",
          roomSize: 18,
          roomSizeUnit: "sqm",
          floor: "1st-3rd Floor",
          view: "City View",
          images: ["/legend.jpg"],
          mainImage: "/legend.jpg",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi"],
          features: ["Work Desk", "Safe"],
          basePrice: 7000,
          currency: "PKR",
          weekendPrice: 8500,
          totalUnits: 8,
          available: true,
        },
        {
          name: "Standard Double Room",
          description: "Comfortable double room with valley views.",
          maxOccupancy: 2,
          adults: 2,
          children: 0,
          bedType: "Double",
          numberOfBeds: 1,
          bedConfiguration: "1 Double Bed",
          roomSize: 22,
          roomSizeUnit: "sqm",
          floor: "4th-6th Floor",
          view: "Valley View",
          images: ["/legend.jpg"],
          mainImage: "/legend.jpg",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar"],
          features: ["Work Desk", "Safe", "Coffee Maker"],
          basePrice: 10000,
          currency: "PKR",
          weekendPrice: 12000,
          totalUnits: 7,
          available: true,
        },
      ]
    },
    {
      name: "Serena Hotel Hunza",
      description: "Luxury hotel in Hunza Valley with panoramic views of Rakaposhi and Ultar peaks.",
      type: "HOTEL" as const,
      address: "Hunza Valley Road",
      city: "Hunza",
      country: "Pakistan",
      state: "GB",
      postalCode: "15710",
      maxGuests: 4,
      bedrooms: 2,
      bathrooms: 2,
      beds: 2,
      basePrice: 18000,
      currency: "PKR",
      cleaningFee: 600,
      serviceFee: 400,
      taxRate: 5,
      images: ["/serena-hunza.jpg"],
      mainImage: "/serena-hunza.jpg",
      amenities: ["WiFi", "Parking", "Restaurant", "AC", "Room Service", "Spa", "Gym"],
      propertyFacilities: ["Restaurant", "Spa", "Gym", "Business Center", "Concierge", "Gift Shop"],
      safetyFeatures: ["24/7 Security", "CCTV", "Fire Safety", "First Aid", "Medical Services"],
      accessibility: ["Wheelchair Access", "Elevator", "Accessible Rooms", "Ramp Access"],
      houseRules: ["No Smoking", "No Pets", "Check-in: 15:00", "Check-out: 11:00"],
      ownerId: propOwnerId,
      approvalStatus: "APPROVED" as const,
      available: true,
      isFeatured: true,
      isVerified: true,
      starRating: 5,
      totalRooms: 40,
      rating: 4.8,
      reviewCount: 65,
      slug: "serena-hotel-hunza",
      checkInTime: "15:00",
      checkOutTime: "11:00",
      cancellationPolicy: "Flexible",
      roomTypes: [
        {
          name: "Superior Room",
          description: "Elegant room with modern amenities and mountain views.",
          maxOccupancy: 2,
          adults: 2,
          children: 0,
          bedType: "King",
          numberOfBeds: 1,
          bedConfiguration: "1 King Bed",
          roomSize: 32,
          roomSizeUnit: "sqm",
          floor: "2nd-5th Floor",
          view: "Mountain View",
          images: ["/serena-hunza.jpg"],
          mainImage: "/serena-hunza.jpg",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar", "Balcony"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer", "Sitting Area"],
          basePrice: 15000,
          currency: "PKR",
          weekendPrice: 18000,
          totalUnits: 20,
          available: true,
        },
        {
          name: "Deluxe Suite",
          description: "Spacious suite with separate living area and premium mountain views.",
          maxOccupancy: 4,
          adults: 2,
          children: 2,
          bedType: "King",
          numberOfBeds: 1,
          bedConfiguration: "1 King Bed + Sofa Bed",
          roomSize: 50,
          roomSizeUnit: "sqm",
          floor: "6th-8th Floor",
          view: "Panoramic Mountain View",
          images: ["/serena-hunza.jpg"],
          mainImage: "/serena-hunza.jpg",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar", "Balcony", "Separate Living Area"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer", "Sitting Area", "Dining Table", "Premium Toiletries"],
          basePrice: 22000,
          currency: "PKR",
          weekendPrice: 28000,
          totalUnits: 12,
          available: true,
        },
        {
          name: "Presidential Suite",
          description: "Ultra-luxurious suite with private terrace and breathtaking views.",
          maxOccupancy: 6,
          adults: 4,
          children: 2,
          bedType: "King",
          numberOfBeds: 2,
          bedConfiguration: "2 King Beds",
          roomSize: 85,
          roomSizeUnit: "sqm",
          floor: "9th Floor",
          view: "360° Mountain View",
          images: ["/serena-hunza.jpg"],
          mainImage: "/serena-hunza.jpg",
          amenities: ["Private Bathroom", "Air Conditioning", "Flat Screen TV", "WiFi", "Mini Bar", "Private Terrace", "Separate Living Area", "Dining Room"],
          features: ["Work Desk", "Safe", "Coffee Maker", "Hair Dryer", "Sitting Area", "Dining Table", "Premium Toiletries", "Jacuzzi"],
          basePrice: 35000,
          currency: "PKR",
          weekendPrice: 42000,
          totalUnits: 3,
          available: true,
        },
      ]
    },
  ];

  // Create properties with room types
  for (const propertyData of properties) {
    const { roomTypes, ...propertyFields } = propertyData;
    
    const property = await prisma.property.create({
      data: propertyFields
    });

    // Create room types for this property
    if (roomTypes && roomTypes.length > 0) {
      for (const roomTypeData of roomTypes) {
        await prisma.roomType.create({
          data: {
            ...roomTypeData,
            propertyId: property.id
          }
        });
      }
      console.log(`✅ Created ${property.name} with ${roomTypes.length} room types`);
    } else {
      console.log(`✅ Created ${property.name} (single-unit property)`);
    }
  }

  console.log("✨ Properties seeded successfully!");
}

